export default {
  plugins: ['@trivago/prettier-plugin-sort-imports'],
  trailingComma: 'all',
  singleQuote: true,
  semi: true,
  importOrder: [
    '^@/pages',
    '^@/components',
    '^@/components/Widgets',
    '^@/components/UI',
    '^@/hooks',
    '^@/utils',
    '^@/api',
    '^@/common',
    '^@/types',
    '^@/constants',
    '^@/assets',
    '^@/styles',
    '^[./]',
  ],
  importOrderSeparation: false,
  importOrderSortSpecifiers: true,
  printWidth: 100,
};
