import type { Metadata } from 'next';
import './globals.scss';
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';
import { Locales } from '@/i18n/i18nConfig';
import HeaderLarge from '@/components/HeaderLarge';
import { CookieAgreement } from '@/components';
import ServiceWorkerRegister from '@/components/ServiceWorkerRegister/ServiceWorkerRegister';
import { TabletHeader } from '@/components/TabletHeader';

export const metadata: Metadata = {
  title: 'Gideone',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: Locales }>;
}>) {
  const { locale } = await params;

  // console.log('params =============================> ' + locale);
  return (
    <html lang={locale}>
      <body data-theme='dark' id='root'>
        <Header locale={locale} />
        <HeaderLarge locale={locale} />
        <TabletHeader locale={locale} />
        {children}
        <ServiceWorkerRegister />
        <CookieAgreement />
        <Footer locale={locale} />
      </body>
    </html>
  );
}
